<?php require __DIR__ . '../../header.phtml' ?>
<?php if (isset($flash['success'])): ?>
    <?php foreach ($flash['success'] as $message): ?>
        <div class="alert alert-success" role="alert">
            <?= $message ?>
        </div>
    <?php endforeach ?>
<?php endif ?>
<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $url['name'] ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $url['id'] ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $url['name'] ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $url['created_at'] ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</main>
<?php require __DIR__ . '../../footer.phtml' ?>