<?php if (isset($flash['success'])): ?>
    <?php foreach ($flash['success'] as $message): ?>
        <div class="alert alert-success" role="alert">
            <?= $message ?>
        </div>
    <?php endforeach ?>
<?php endif ?>
<?php if (isset($flash['warning'])): ?>
    <?php foreach ($flash['warning'] as $message): ?>
        <div class="alert alert-warning" role="alert">
            <?= $message ?>
        </div>
    <?php endforeach ?>
<?php endif ?>
<?php if (isset($flash['error'])): ?>
    <?php foreach ($flash['error'] as $message): ?>
        <div class="alert alert-danger" role="alert">
            <?= $message ?>
        </div>
    <?php endforeach ?>
<?php endif ?>